### ISSUE TITLE
Simplify adding annotations to the manifest

### ISSUE THREAD

**Issue by rjaegers** [philips-software/amp-devcontainer#202]
Per #201 annotations have been added to the manifest/index file. The way this is done is rather cumbersome at the moment. When https://github.com/docker/build-push-action/issues/958 is solved by means of https://github.com/docker/build-push-action/pull/992, together with https://github.com/docker/metadata-action/pull/351, we can simplify this:

https://github.com/philips-software/amp-devcontainer/blob/1afec52553fe286d12997daf0c0acdd63fd2c77d/.github/workflows/build-push.yml#L58-L70

to:

```
- uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
  id: build-and-push
  with:
    file: .devcontainer/Dockerfile
    platforms: linux/amd64,linux/arm64
    push: ${{ github.event_name != 'merge_group' }}
    tags: ${{ steps.meta.outputs.tags }}
    labels: ${{ steps.meta.outputs.labels }}
    annotations: ${{ steps.meta.outputs.labels }}
    sbom: true
    provenance: true
    cache-from: type=gha
    cache-to: type=gha,mode=max
```

And remove this:

https://github.com/philips-software/amp-devcontainer/blob/1afec52553fe286d12997daf0c0acdd63fd2c77d/.github/workflows/build-push.yml#L45-L49
